### ISSUE TITLE
Unhandled exception: Crash on startup

### ISSUE THREAD

**Issue by Nightengale537** [DazedNConfused-/CDDA-Game-Launcher#70] opened 2022-10-07 23:58 UTC
* Description: Open launcher from a shortcut on my desktop it loads as normal until the launcher screen appears it crashes the end.
* Version: 1.6.7
* OS: Windows-10-10.0.19044-SP0 (64-bit)
* Type: `<class 'AttributeError'>`
* Value: 'NoneType' object has no attribute 'split'
* Traceback:
```
  File "C:\Program Files (x86)\CDDA Game Launcher\cddagl\ui\views\main.py", line 1412, in showEvent
    self.refresh_builds()
  File "C:\Program Files (x86)\CDDA Game Launcher\cddagl\ui\views\main.py", line 3266, in refresh_builds
    self.refresh_changelog()
  File "C:\Program Files (x86)\CDDA Game Launcher\cddagl\ui\views\main.py", line 3292, in refresh_changelog
    body = entry['body'].split('####'),

```

**Comment by Xenikos** [comment] 2022-10-08 12:00
I can confirm that you are not the only one experiencing this issue.

Traceback:
File "E:\Users\X\AppData\Local\Programs\CDDA Game Launcher\cddagl\ui\views\main.py", line 1412, in showEvent

self.refresh_builds()
File "E:\Users\X\AppData\Local\Programs\CDDA Game Launcher\cddagl\ui\views\main.py", line 3266, in refresh_builds
self.refresh_changelog()
File "E:\Users\X\AppData\Local\Programs\CDDA Game Launcher\cddagl\ui\views\main.py", line 3292, in refresh_changelog
body = entry['body'].split('####'),

**Comment by RundownRhino** [comment] 2022-10-09 22:57
This is a duplicate of #65, the comments here have a workaround.

**Comment by Nightengale537** [comment] 2022-10-09 23:00
I realized that when I looked around after posting my crash log your work around works pretty well

**Comment by DazedNConfused-** [comment] 2022-10-18 21:20
Fixed in https://github.com/DazedNConfused-/CDDA-Game-Launcher/releases/tag/v1.6.8 thanks to @RundownRhino

**Closed by DazedNConfused-** 2022-10-18 21:20 UTC
